"""add external_id to transactions

Revision ID: d97542daf496
Revises: 1155007d046b
Create Date: 2026-05-02 14:05:24.999613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97542daf496'
down_revision: Union[str, Sequence[str], None] = '1155007d046b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_id', sa.String(length=128), nullable=True))
    op.create_index('ux_transactions_external_id', 'transactions', ['external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_transactions_external_id', table_name='transactions', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('transactions', 'external_id')
    # ### end Alembic commands ###
